locking/rwsem: Fix introduce basis for down_write_killable()
* Fix commit https://github.com/zeta96/L_keramel_santoni/commit/d794bc203c280a78ebc5f19644cfc33bc991cfeb

               from ../arch/arm64/kernel/asm-offsets.c:21:
../include/asm-generic/rwsem.h: In function '__down_write_killable':
../include/asm-generic/rwsem.h:70:8: error: implicit declaration of function 'atomic_long_add_return_acquire'; did you mean 'atomic_add_return_acquire'? [-Werror=implicit-function-declaration]
   70 |  tmp = atomic_long_add_return_acquire(RWSEM_ACTIVE_WRITE_BIAS,
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |        atomic_add_return_acquire
cc1: some warnings being treated as errors
make[2]: *** [.././Kbuild:82: arch/arm64/kernel/asm-offsets.s] Error 1